services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: image_proc_db
      POSTGRES_USER: eemil
      POSTGRES_PASSWORD: elShen10642612
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U eemil -d image_proc_db']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio_local
    ports:
      - '9000:9000' # Port API (pour ton code/boto3)
      - '9001:9001' # Port Console (Interface Web)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    # La commande lance le serveur et d√©finit le port de la console
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data # Persistance des images
    restart: unless-stopped

  api:
    build: .
    volumes:
      - .:/app
      - ./Media:/app/Media
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://eemil:elShen10642612@db:5432/image_proc_db

volumes:
  postgres_data:
